name: animeflv
description: An animeflv.net api that allows you to retrieve different data from the animeflv catalog, and use it inside your own app or code using dart.
version: 0.0.4
homepage: https://github.com/raulidg33/animeflv.dart

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  http: ^0.13.4
  html: ^0.15.0
  quiver: ^3.0.1+1
  beautiful_soup_dart: ^0.2.0